@IsTest
public class TrialCustomerPortal_Test {
    
    @IsTest 
    static void testMethode1(){
        TrialCustomerPortalHomePageController Cls = new TrialCustomerPortalHomePageController();
        
        Cls.SortProducts();
        Cls.SortProducts();
        
        Cls.SortCases();
        Cls.SortCases();
        
        Cls.SortSolutions();
        Cls.SortSolutions();
        
        Cls.SortIdeas();
        Cls.SortIdeas();
        
        
    }

}