public class WrpDataAccountToRcu {

    public String Pays {get; set;}
    public String CompteId {get; set;}
    public String IdSalesForce {get; set;}
    public String Email {get; set;}
    public String NumCarteFidelite {get; set;}
    public String NumCarteUI {get; set;}
    public String Nom {get; set;}
    public String Prenom {get; set;}
    public Date Date_Naissance {get; set;}
    public String Civilite {get; set;}
    public String Adresse_Num_Voie {get; set;}
    public String Adresse_Type_Voie {get; set;}
    public String Adresse_Appartement {get; set;}
    public String Adresse_Escalier {get; set;}
    public String Adresse_Immeuble {get; set;}
    public String Adresse_Residence {get; set;}
    public String Adresse_Nom_Voie {get; set;}
    public String Adresse_Code_Postal {get; set;}
    public String Adresse_Ville {get; set;}
    public String Adresse_Pays {get; set;}
    public String Telephone_Fixe {get; set;}
    public String Telephone_Portable {get; set;}
    public DateTime Date_Creation {get; set;}
    public DateTime Date_Modification {get; set;}
        
}