/**
 * Container for custom fields of a Subscription Product Feature object.\n
 */
public class zc_SubscriptionProductFeatureObject { //extends HashMap<String, Object> {
    public static zc_SubscriptionProductFeatureObject getExample() {
        zc_SubscriptionProductFeatureObject subscriptionProductFeatureObjectCustomFields = new zc_SubscriptionProductFeatureObject();
        return subscriptionProductFeatureObjectCustomFields;
    }

    // public Boolean equals(Object obj) {
    //     if (obj instanceof zc_SubscriptionProductFeatureObject) {
    //         zc_SubscriptionProductFeatureObject subscriptionProductFeatureObjectCustomFields = (zc_SubscriptionProductFeatureObject) obj;
    //         return ;
    //     }
    //     return false;
    // }

    public Integer hashCode() {
        Integer hashCode = 43;
        return hashCode;
    }
}