/**
 * zc_ZObject
 */
public virtual class zc_ZObject { //} extends HashMap<String, Object> {
    
    public Map<String, Object> zObject {get; set;}

    
    // public static zc_ZObject getExample() {
    //     zc_ZObject zObject = new zc_ZObject();
    //     return zObject;
    // }

    // public Boolean equals(Object obj) {
    //     if (obj instanceof zc_ZObject) {
    //         zc_ZObject zObject = (zc_ZObject) obj;
    //         return ;
    //     }
    //     return false;
    // }

    public Integer hashCode() {
        Integer hashCode = 43;
        return hashCode;
    }
}